### ISSUE TITLE
I uninstalled the plugin and I cannot type anything in to ChatGPT

### ISSUE THREAD

**Issue by keatshandwriting** [C-Nedelcu/talk-to-chatgpt#131]
I uninstalled the plugin and I cannot type anything in to ChatGPT
I write at the prompt and then it displays nothing (probably looking for audio input). Help! ChatGPT is unusable !

Loom video here --> https://www.loom.com/share/d4686f5b9ed046cfa3d6487cc8054bf8 please help in leau of one star this is very disappointing that Talk To Chat GPT broke ChatGPT

**Comment by keatshandwriting** [comment]
I cleared cache (logged me out) logged back in,, cleared microphone settings ... ?

**Comment by tadeogutierrez** [comment]
this bug is caused by the changes chatgpt made to the send button. If you type any character in the text area after the extension inserts the text in the text area the button wil turn gren and you can click it manually, Anyway, this should be modified accordingly in the extension since the button is no longer working with Talk-to-chatgpt

**Comment by C-Nedelcu** [comment]
hello,

Thank you for your feedback.
I've released a new version, v2.6.1, which fixes this. 

I recommend doing a manual install for now (instructions are on the project home page)
Or else, simply wait until the update is approved on the Chrome store. From my estimate, it should be on Tuesday or Wednesday.

**Comment by C-Nedelcu** [comment]
other issues you might have with writing and sending text in the prompt are not related to Talk-to-ChatGPT but may be caused by other extensions.

All this extension does is put some text in the box and try to send it. 

If ChatGPT doesn't work even after disabling this extension, then the problem cannot be originating from this extension, simple as that. It's possible you have another extension that is causing issues.

Try using incognito mode, or Edge, or creating a new Chrome profile without any other extensions, etc?

**Comment by C-Nedelcu** [comment]
v2.6.1 is live on Chrome extension store. Confirmed fixing the issue

**Comment by keatshandwriting** [comment]
Thanks I finally tried Chat GPT on Chrome after using in FIreFox, i can type now... thanks guys...
