### ISSUE TITLE
Default position blocking the Share Chat button

### ISSUE THREAD

**Issue by 7k50** [C-Nedelcu/talk-to-chatgpt#163]
Hi,

OpenAI has changed the "Share Chat" button from the side bar to the top right corner. The default location of the talk-to-chatgpt menu is obscuring this button.

I realize that the talk-to-chatgpt menu can possibly be moved/dragged elsewhere, but it wasn't a very smooth operation for me in Chrome, and it would be ideal to just place it elsewhere (e.g. just below the "Share Chat" button).

**Comment by C-Nedelcu** [comment]
I left this out from v2.7.0 unfortunately (I had to focus on the ElevenLabs critical issues) but I will definitely implement this in v2.7.1 shortly. Sorry !

**Comment by C-Nedelcu** [comment]
Hello,
I've published v2.7.1 - pending approval on Chrome and Edge stores, manual install only for now
- Updated: initial position of the widget lowered a bit so that the ChatGPT 'Share Chat' icon is visible (#163)
- Updated: in the ElevenLabs voice list, it is possible to select v1 or v2 multilanguage model
- Fixed: monolingual voices in ElevenLabs didn't work in v2.7.0 due to a mistake in the API code

**Comment by C-Nedelcu** [comment]
v2.7.1 is now available on the Chrome store and fixes this.
I am closing the Issue, feel free to reopen in case you are still having trouble (with v2.7.1)
