### ISSUE TITLE
broken for Korean

### ISSUE THREAD

**Issue by nyck33** [C-Nedelcu/talk-to-chatgpt#172]
I use Korean input voice and Google Korean output voice but I have to refresh the browser often and frequently then it never picks anything up.  Pretty useless extension.

**Comment by C-Nedelcu** [comment]
> I use Korean input voice and Google Korean output voice but I have to refresh the browser often and frequently then it never picks anything up. Pretty useless extension.

Hello,
There are over 230,000 active users and the extension has received several hundreds 5-star reviews.
Don't you think there may be a tiny chance that the problem is on your side?
Most people who have issues are those who install other extensions that create conflicts.
I am not sure what your intention here is - get assistance and get your problem fixed, or just be insulting to the developers who spent months creating something in their free time and which you are not even being charged for?

**Comment by nyck33** [comment]
Those are straw man arguments, you should publish which extensions can conflict and some results of testing each language combination in different browsers..  I do have that ChatGPT power activated, think I deactivated Prometheus but again without proper documentation and you guys asking users like me not to give you one star but to raise issues and then you use straw man arguments here, that is pathetic.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by C-Nedelcu** [comment]
So the problem *was* on your side... 
Thanks - issue closed !

PS: you have made quite a fool of yourself and under your public name (Nobutaka Kim) 
I would advise changing your tone if you really want to get anything done in life
