### ISSUE TITLE
Problem with mic

### ISSUE THREAD

**Issue by Marek-Jeziorski** [C-Nedelcu/talk-to-chatgpt#178]
The microphone freezes frequently. Usually, after the first answer, it no longer hears me. I installed another plugin of this type and it works without any problems. But overall your add-on is better ;-)

**Comment by C-Nedelcu** [comment]
hello,
I have attempted to fix this in v2.7.0
as of this message, v2.7.0 is currently pending approval on Chrome/Edge stores, but you can install it manually to try.
the manual installation method is described on the homepage.

Please let me know if v2.7.0 fixes this issue? 
For me everything works fine after hours of testing - both with browser text-to-speech and ElevenLabs

**Comment by jackokiwi** [comment]
Thanks for the fix. I just did the manual install into chrome and restarted chrome. I can see the 2.7 plugin is installed. When I go to click on Start nothing happens. I am wondering if I installed correctly. I unpacked the zipped file into a folder and clicked on that folder which installed the plugin, but the process was not like your help me file. Sorry to be a pain. Thanks, David

**Comment by C-Nedelcu** [comment]
> Thanks for the fix. I just did the manual install into chrome and restarted chrome. I can see the 2.7 plugin is installed. When I go to click on Start nothing happens. I am wondering if I installed correctly. I unpacked the zipped file into a folder and clicked on that folder which installed the plugin, but the process was not like your help me file. Sorry to be a pain. Thanks, David

you are not a pain at all, on the contrary, I appreciate that you are taking the time to help figure out the issues.

In order to help you, I would need the answer to this series of standard questions :

1) What version are you using ? **=> v2.7.0**

2) What web browser and OS are you using - please indicate the name and version?

3) Can you please put a screenshot showing all your current settings (hide the ElevenLabs API key if relevant) ? 

4) Can you please copy and paste here the console log (this can be found in the Chrome developer tools, open the "Console" tab, then copy everything) ?

5) What other ChatGPT plugins are you using?

6) A lot of the times, other intrusive plugins conflict with normal use and generate unexpected behavior. Have you tried disabling all ChatGPT-related plugins except Talk-to-ChatGPT ?

**Comment by jackokiwi** [comment]
Kia ora

 

I turned off all the Chrome apps for ChatGPT and bingo away it went. Thanks. Happy

 

 

Warm regards

 

David A. Jack MSc QG®

Qualified Genealogist

17b Royal Arcade

Timaru, 7910

New Zealand

Mobile: 021 770000

 <http://www.research.gen.nz/> www.research.gen.nz

 

Director 

Register of Qualified Genealogists

www.qualifiedgenealogists.org
