### ISSUE TITLE
404 error 

### ISSUE THREAD

**Issue by OpMisOp234** [C-Nedelcu/talk-to-chatgpt#180]
I was unable to add the ChatGPT Chrome extension to my desktop from the Chrome Web Store. I am due to submit a project that I created using ChatGPT based on your extension, and I am unsure of how to proceed. Please advise me on what steps I should take.

![Screenshot_2023-09-17-20-03-00-38_4d38fce200f96aeac5e860e739312e76](https://github.com/C-Nedelcu/talk-to-chatgpt/assets/145274323/e2b49c7a-623e-448c-8fd3-9432d54f8087)

**Comment by OpMisOp234** [comment]
I installed it manually, thank you.

**Comment by PaperOrb** [comment]
That's a workaround, but this issue should have been left open since it's still an issue.

**Comment by C-Nedelcu** [comment]
The current version on the Chrome store was not working properly due to an update from OpenAI which disabled the ElevenLabs functionality. As a result I was getting review-bombed with 1 star reviews from frustrated users (understandably). I decided to take it down momentarily, until the newest version is approved.

Meanwhile those who still want to use the extension can install it manually (v2.7.1 as of today) installation instructions are on the project home page.

**Comment by PaperOrb** [comment]
@C-Nedelcu Thanks. Can linux users install manually or is that windows only?

**Comment by C-Nedelcu** [comment]
> @C-Nedelcu Thanks. Can linux users install manually or is that windows only?

I am quite certain that Linux users can install manually as well. Everything is purely javascript.

**Comment by C-Nedelcu** [comment]
v2.7.1 is now available on the Chrome store and fixes this.
I am closing the Issue, feel free to reopen in case you are still having trouble (with v2.7.1)
