### ISSUE TITLE
Really appreciate your Chrome Extension

### ISSUE THREAD

**Issue by 61t** [C-Nedelcu/talk-to-chatgpt#41]
It's running smoothly. Thanks first. 

I was wondering if you can add a new feature of supporting personal GCP/Azure API key to use more natural sounds. 

One example is AwesomeTTS which is an Anki plugin to do exactly what I proposed. 
https://github.com/AwesomeTTS/awesometts-anki-addon

Maybe you can just "COPY" AwesomeTTS's business model and then charge a fee for people who don't want to manage CLOUD 
 API but still want better natural sounds for ChatGPT.

**Comment by Giganoob23** [comment]
This is exactly what I came here to say. We need more realistic voices to make the experience more immersive. The technology is already there. ElevenLabs etc... It's sad for such a great extension to hear voices from 1990 tech

**Comment by C-Nedelcu** [comment]
There is an issue with how most TTS APIs work and a reason why I can only get this to work properly under Chrome at the moment. In Chrome, you can basically push sentences to the TTS API stack, and the API will manage on its own. You can push several sentences at once, even while the current sentence is being spoken. The added sentences just pile up and are spoken one after the other.

From my trials with other APIs, they behave like this:
- can't push another sentence while the current one is being spoken (the API just rejects it)
- if you push two sentences consecutively, they will be spoken at the same time (so it sounds like garbage)

What's more, the scope of this addon is quite limited, it's basically an API experiment. It's in no way a long term professional product. I am happy to let anyone pick up the project and turn it into something greater, but I clearly lack the time and involvement to take this extension to the heights some users would want. The main issue being that with every update and iteration of ChatGPT, we come closer to an end. They will inevitably change the UI completely and the whole extension will become moot. And eventually, they will hopefully add proper TTS / STT functionality so that an extension like mine isn't needed.

These are the reasons why I am not currently considering adding external voices to the project. This project was basically to connect ChatGPT to the Chrome APIs (TTS/STT) and not much more. That being said I will gladly accept contributions to the projects, or forks, if anyone is willing to go down that road.

**Comment by hrocha** [comment]
Thank you for this excellent extension.  If you use Edge as your browser, you can access Microsoft's Natural AI voices and they sound excellent.  All Chrome extensions are usable in Edge.  Very natural sounding voices and they have them for almost all languages, a male and female version.  I'm using a Windows 11 machine, with Bing as my search Engine and Edge Dev as my browser.

**Comment by C-Nedelcu** [comment]
Hello there,

I have added ElevenLabs API support in v2.6.0.

This version has not been submitted to the Chrome/edge stores yet, I think it would need some beta testing first.
Would anyone please give it a try?

You have to install the new version manually, instructions are given on the project's home page.

I hope you enjoy it. I had fun testing it, the ElevenLabs voices are pretty great - even the default ones with a Free account.

**Comment by C-Nedelcu** [comment]
this has been live for a few days and seems to be working pretty great, so I'm going to close the issue :)
