### ISSUE TITLE
talk to chatgpt and AIPRM gets a little messy, PLEEEZ help, its so important to me <3 (im a girl btw)

### ISSUE THREAD

**Issue by Kmanqt11** [C-Nedelcu/talk-to-chatgpt#47]
aiprm is amazing extension for gpt, i use it to control the output language of chatgpt, and also the tone and writing style, but it also adds a "continue" button, that totally fucks over talktochatgpt's manually send (thru voice) or automatic sending message because for some reason it triggers the continue button now instead of just sending the msg, so a chrome browser prompt pops up and asks me if im sure i want to discard prompt, fucks over everything and all my hopes and dreams plz help its a small thing but makes a huge problkem for  me

**Comment by C-Nedelcu** [comment]
I am sorry that my extension creates conflicts with other extensions. Unfortunately I won't be able to deal with that sort of thing. I recommend using the extensions separately. Use Talk-To-ChatGPT on Chrome (or Edge, because apparently now it works on Edge too?) and your other extensions on Firefox, for example.
