### ISSUE TITLE
Can a user hold a conversation with the bot in a different language?

### ISSUE THREAD

**Issue by rrzhang139** [C-Nedelcu/talk-to-chatgpt#50]
Essentially, can the user's voice input and the chat output be in the same language such that you can hold a conversation in a new language? I am able to make commands in English and the bot will respond in mandarin, but how do I make commands in new languages?

**Comment by C-Nedelcu** [comment]
I'm afraid I don't understand your question. You can choose the speech recognition language in the settings, so that way, you can speak to the bot in any language that you want. If you want the bot to reply in a different language:
1- instruct the bot to reply in the language you want. (example: say "please reply in Spanish")
2- make sure to select the language you want for the bot's voice in the settings window
