### ISSUE TITLE
When this extensions can use in Andorid

### ISSUE THREAD

**Issue by joe12801** [C-Nedelcu/talk-to-chatgpt#77]
When this extensions can use in Andorid,such as  in kiwi brower, coz more users use  Andorid phone
when you are free,can condiser this

**Comment by C-Nedelcu** [comment]
hello,
sorry, but the browser you requested does not support the necessary APIs for this

as per the FAQ:

Q: Which web browsers are supported? A: This extension is designed for Google Chrome and Microsoft Edge, desktop version only. The extension will not work in any other web browser, especially not mobile browsers, because these browsers do not support the necessary APIs for speech recognition and speech synthesis.
