### ISSUE TITLE
not read the text if genetarion is begin before click play button

### ISSUE THREAD

**Issue by hdpklm** [C-Nedelcu/talk-to-chatgpt#87]
Hello

I have some problems

1- its not read the text if I click on generate befor click on play button
2- not read regeneration text
3- when I change between chats in history list, or create new chat, its not read, I think its record the index of last block and read when generate a new one.
4- I need a button in the generate text to reread

thank you

**Comment by C-Nedelcu** [comment]
The messages read by the extension are the new messages that are being received. It doesn't read the history.

It's meant to create human-like interaction: you speak to ChatGPT, it speaks back to you.

This is by design.

If you are having issue with text-to-speech I suggest using the latest version in Google Chrome. V2.5.0 has been published just yesterday and fixes some issues with the text-to-speech API. If you still have issues, try switching to a different language/voice in the settings.

**Comment by hdpklm** [comment]
@C-Nedelcu
ok thank you 👍
