### ISSUE TITLE
Add a Trigger Word for voice Activation

### ISSUE THREAD

**Issue by SpicyDoritos** [C-Nedelcu/talk-to-chatgpt#89]
I love this great job random thought for a feature how about Something similar to Alexa or Googles Trigger words to activate the listening so it can be used more as an assistant vs it picking up everything you say as an input

**Comment by C-Nedelcu** [comment]
Hello,

The initial kickstart of Talk-to-ChatGPT has to come from a manual click OR a key press, because Chromium-based browsers do not allow speech recognition activation without a user input (this would be a security issue if you visit any website and they start picking up your audio without you doing anything)
more information: https://stackoverflow.com/questions/54265423/javascript-speechsynthesis-speak-without-user-activation-is-no-longer-allowed

So, after the extension has been started, you can simply pause using a vocal command, and use the same pause word to unpause whenever you need it.

1. Open the settings. Set the pause word to "OK chatty" and enable the option called "Keep listening when paused"
2. Say "OK chatty" to pause
3. Say "OK chatty" when you are ready to speak to ChatGPT again
4. repeat 2 and 3 forever

**Comment by C-Nedelcu** [comment]
I am going to close this because I believe my answer should be satisfactory.
If you disagree or think something else needs to be added, we can reopen it.
